name: Download Steam China Store Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  download-page:
    runs-on: ubuntu-latest

    steps:
    - name: Download Steam China Store Page
      run: |
        curl -o output.html "https://store.steamchina.com" 
        cat output.html
