name: Download Steam China Store Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  download-page:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install cheerio
    - name: Download Steam China Store Page
      run: |
        curl -s "https://store.steamchina.com" | node -e "require('cheerio').load(process.stdin, { xmlMode: true }).html()" | tee -a output.html
        cat output.html
